name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # 只在v开头的标签推送时触发
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Check directory structure
      run: |
        dir
        echo "Creating templates and static directories if they don't exist"
        if (-not (Test-Path -Path "templates")) { New-Item -Path "templates" -ItemType Directory }
        if (-not (Test-Path -Path "static")) { New-Item -Path "static" -ItemType Directory }
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --name EXCEL2XML template.py
        dir dist
        
    - name: Create release ZIP
      run: |
        dir
        dir dist
        Compress-Archive -Path "dist\EXCEL2XML.exe" -DestinationPath "EXCEL2XML.zip"
    
    - name: Extract version from tag
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## EXCEL2XML 发布版本 ${{ steps.get_version.outputs.VERSION }}
          
          ### 功能
          - XML转Excel：支持从XML导出为Excel格式
          - Excel对比：对比两个Excel表格，自动标记新增和修改的内容
          - 自动更新：直接更新目标文件并用颜色标记变更
          
          ### 安装和使用
          1. 下载并解压ZIP文件
          2. 运行EXCEL2XML.exe
          3. 按照界面提示操作
        files: EXCEL2XML.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}